# Generated by Django 5.0.1 on 2024-02-03 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_page', models.CharField(max_length=20)),
                ('about_heading', models.CharField(max_length=100)),
                ('about_image_1', models.ImageField(upload_to='about/')),
                ('about_image_2', models.ImageField(upload_to='about/')),
                ('about_image_3', models.ImageField(upload_to='about/')),
                ('about_image_4', models.ImageField(upload_to='about/')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_image', models.ImageField(upload_to='events')),
                ('event_name', models.CharField(max_length=100)),
                ('event_des', models.CharField(max_length=200)),
                ('event_is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_image', models.ImageField(upload_to='feature/')),
                ('feature_name', models.CharField(max_length=200)),
                ('feature_heading', models.CharField(max_length=200)),
                ('feature_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_image', models.ImageField(upload_to='feedbacks')),
                ('feedback_name', models.CharField(max_length=200)),
                ('feedback_profession', models.CharField(max_length=500)),
                ('feedback_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='products')),
                ('product_name', models.CharField(max_length=200)),
                ('product_price', models.FloatField()),
                ('product_short_description', models.CharField(max_length=500)),
                ('product_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_image', models.ImageField(upload_to='slides')),
                ('slide_title', models.CharField(max_length=30)),
                ('slide_description', models.CharField(blank=True, max_length=100)),
                ('slide_is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
