# Generated by Django 5.0.1 on 2024-01-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_slide_slide_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='slide_is_active',
            field=models.BooleanField(default=True),
        ),
    ]
