# Generated by Django 5.0.1 on 2024-01-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_image', models.ImageField(upload_to='events')),
                ('event_name', models.CharField(max_length=100)),
                ('event_des', models.CharField(max_length=200)),
                ('event_is_active', models.BooleanField()),
            ],
        ),
    ]
