# Generated by Django 5.0.1 on 2024-01-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='slide_description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='slide',
            name='slide_title',
            field=models.CharField(max_length=30),
        ),
    ]
