# Generated by Django 5.0.1 on 2024-01-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_slide_slide_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_page', models.CharField(max_length=20)),
                ('about_heading', models.CharField(max_length=100)),
                ('about_image_1', models.ImageField(upload_to='about/')),
                ('about_image_2', models.ImageField(upload_to='about/')),
                ('about_image_3', models.ImageField(upload_to='about/')),
                ('about_image_4', models.ImageField(upload_to='about/')),
            ],
        ),
    ]
